name:                servant-clay
version:             0.0.0.1
github:              "l-monnier/servant-clay"
license:             BSD3
author:              "Leonard Monnier"
maintainer:          "leonard.monnier@gmail.com"
copyright:           "2023 Leonard Monnier"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/l-monnier/servant-clay#readme>

dependencies:
- base >= 4.9 && < 5
- bytestring
- clay
- http-media
- servant
- template-haskell
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  servant-clay-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-clay

tests:
  servant-clay-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-clay
